spring:
  datasource:
    url: jdbc:mysql://localhost/jelibank?serverTimezone=America/Bogota
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jeifer05*.
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org:
      hibernate:
        SQL: debug

